### ISSUE TITLE
[Yahoo] Ads are not counted if they are opened in a new tabs with middle click

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [past/searchvolmodel#16]
[Affected versions]:
- Nightly 58.0a1
- Beta 57.0b5
- Release 56.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "extensions.searchvolmodel.logging" pref is set to 40 (integer) on a clean new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and focus the address bar.
2. Perform a search with Yahoo that will generate ad links.
3. Middle click one of the adverts.
4. Verify the telemetry pings.

[Expected result]:
- A single ping is logged.

[Actual result]:
- No ping is logged.

[Notes]:
- The issue is not reproducible if you open an advert in a New Tab with ctrl/cmd+click or if you use the context menu option.
- The issue is not reproducible on Google, I can't verify Bing because of #11.
- Attached a screen recording of the issue:
![middle clicks on yahoo are not counted](https://user-images.githubusercontent.com/18304511/31230398-8fc027fe-a9ec-11e7-9ef1-cfff5cd1643a.gif)

**Comment by past** [comment]
I believe the root cause here is the same as in #17 and the add-on is working properly.
