### ISSUE TITLE
[Yahoo] Ads are not counted if the an ad link is dragged to the Tab bar

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [past/searchvolmodel#17]
[Affected versions]:
- Nightly 58.0a1
- Beta 57.0b5
- Release 56.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "extensions.searchvolmodel.logging" pref is set to 40 (integer) on a clean new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and focus the address bar.
2. Perform a search with Yahoo that will generate ad links.
3. Drag an ad link to the tab bar and release the mouse.
4. Verify the telemetry pings.

[Expected result]:
- The action is not counted.

[Actual result]:
- The action is counted.

[Notes]:
- The issue is not reproducible on Google, I can't verify Bing because of #11.
- Attached a screen recording of the issue:
![dragging links to tabs are not counted on yahoo](https://user-images.githubusercontent.com/18304511/31230407-991e9132-a9ec-11e7-9c7c-ff34882886e9.gif)

**Comment by past** [comment]
I just debugged this and the add-on is doing the right thing. Google marks the visit on mouse down whereas Yahoo marks it on click. Dragging the link only generates a mouse down event, not a click event.

**Comment by past** [comment]
Bing is counted properly as it redirects to mark the visit.
