### ISSUE TITLE
Missing distribution ID

### ISSUE THREAD

**Issue by past** [past/searchvolmodel#19]
Apparently distributionId is not set properly in the searchvol ping. We need to investigate probably using one of the FC builds.

**Comment by Standard8** [comment]
There's a couple of issues here:

1) We have code in bootstrap.js that attempts to detect that it is a distribution and not enable telemetry if that's the case:

https://github.com/past/searchvolmodel/blob/7509115ac8822112f577dc35f05cc934ac0336b0/add-on/bootstrap.js#L126

From debugging, that doesn't work, as the telemetry is being enabled. I suspect it doesn't work as it could be too early in the startup process. We don't need it anyway, so I can remove that.

2) For the telemetry ping itself, we're attempting to use `Cc["@mozilla.org/xre/app-info;1"].getService(Ci.nsIXULRuntime).distributionId` which is wrong on two counts - first it should be `distributionID` secondly, that's not the actual distribution id we want (it'd be `org.mozilla`).

We need to get the value from the preference, the same as for the rest of gecko. By the time we log telemetry, it should be defined correctly.
