### ISSUE TITLE
Ad clicks are not registered if they come from keyboard

### ISSUE THREAD

**Issue by Softvision-VladBacia** [past/searchvolmodel#3]
[Affected versions]:

- Firefox Nightly 57.0a1
- Search Volume Modeling v0.0.1

[Affected Platforms]:

- All Windows
- All Mac OS
- All Linux

[Prerequisites]:

- Latest Search Volume Modeling v0.0.1 was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Make a search in the browser that returns multiple ads.
3. Press "Tab" keyboard button until an Ad is selected.
4. Press "Enter" keyboard button.

[Expected result]:

- The Ad is opened in the same tab and the "ad click" is registered. 

[Actual result]:

- The "ad click" is not registered.

**Comment by Standard8** [comment]
I can reproduce this with Google, but not Yahoo. From what I can tell, if you use use keyboard on google's site, then it doesn't go to the ad server. There's a ping of some sort to their servers, but not the ad one.

**Comment by past** [comment]
My understanding is that ad click tracking is done using mousedown and touchstart events, so in the case of keyboard selection the ad visit is not counted.
