### ISSUE TITLE
Google only has 2 buckets for ad clicks

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [past/searchvolmodel#4]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "searchvolmodel" add-on is installed on a clean new profile

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and focus the address bar.
2. Perform a search with Google that will generate ad links.
3. Click on an ad link.
4. Repeat Step 2 and 3 using the toolbar search bar, about:newtab search bar and about:home search bar.
5. Verify the counters.

[Expected result]:
- A separate bucket is created for each different search bar used.

[Actual result]:
- Only two buckets are created.

[Notes]:
- The issue is not reproducible with Bing and Yahoo, in those cases 4 buckets are created.
- Here is a list of all the buckets:

Yahoo: yahoo.adclick:unknown:yhs-001, yahoo.adclick:unknown:yhs-002, yahoo.adclick:unknown:yhs-003, yahoo.adclick:unknown:yhs-004
![image](https://user-images.githubusercontent.com/18304511/29672935-556c82e4-88f6-11e7-9af4-33a26b4fd789.png)

Bing: bing.adclick:unknown:MOZTSB, bing.adclick:unknown:MOZSPG, bing.adclick:unknown:MOZSBR, bing.adclick:unknown:MOZLBR
![image](https://user-images.githubusercontent.com/18304511/29673165-0ebc48ec-88f7-11e7-9c61-296c8e71d958.png)

Google: google.adclick:unknown:firefox-b, google.adclick:unknown:firefox-b-ab
![image](https://user-images.githubusercontent.com/18304511/29673297-7ab54940-88f7-11e7-9daa-b4996951794f.png)

**Comment by past** [comment]
@mkaply this is expected, right?

**Comment by mkaply** [comment]
Yes, this is correct. We only have separate codes for the search bar and the url bar. See:

http://searchfox.org/mozilla-central/source/browser/locales/searchplugins/google.xml

For Yahoo and Bing, we have separate codes for all search locations.

**Comment by past** [comment]
Thanks Mike!
